"use client";

import { useState } from "react";
import { managerApi } from "@/lib/apiClient";
import toast from "@/lib/toast";
import { formatUSD } from "@/utils/currency";
import ComponentCard from "@/components/common/ComponentCard";
import Button from "@/components/ui/button/Button";
import Input from "@/components/form/input/InputField";
import Label from "@/components/form/Label";
import { InfoIcon, UserIcon, CalenderIcon } from "@/icons";

interface CouponData {
  code: string;
  status?: string;
  generatedBy?: { name: string; email?: string };
  createdAt?: string;
  discount?: number | string;
  discountType?: string;
  honoredBy?: { name: string; email?: string };
  honoredAt?: string;
  expiresAt?: string;
  description?: string;
  customerEmail?: string;
}

export default function ManagerCouponAuditPage() {
  const [couponCode, setCouponCode] = useState("");
  const [couponData, setCouponData] = useState<CouponData | null>(null);
  const [loading, setLoading] = useState(false);
  const [searched, setSearched] = useState(false);

  const handleSearch = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    if (!couponCode.trim()) {
      toast.error("Please enter a coupon code");
      return;
    }

    try {
      setLoading(true);
      setSearched(true);
      const response = await managerApi.searchCoupon(couponCode.trim());
      setCouponData(response.data);

      if (!response.data) {
        toast.error("Coupon not found");
      }
    } catch (error: any) {
      if (error.response?.status === 404) {
        toast.error("Coupon not found");
        setCouponData(null);
      } else {
        toast.error(error.response?.data?.message || "Failed to search coupon");
      }
      console.error("Search coupon error:", error);
    } finally {
      setLoading(false);
    }
  };

  const getStatusColor = (status?: string) => {
    switch (status?.toUpperCase()) {
      case "ACTIVE":
        return "bg-success-100 text-success-800 dark:bg-success-900/30 dark:text-success-400";
      case "HONORED":
        return "bg-brand-100 text-brand-800 dark:bg-brand-900/30 dark:text-brand-400";
      case "EXPIRED":
        return "bg-error-100 text-error-800 dark:bg-error-900/30 dark:text-error-400";
      default:
        return "bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300";
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-800 dark:text-white/90">Coupon Audit</h1>
        <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
          Audit coupon usage and validate transactions
        </p>
      </div>

      {/* Search Form */}
      <ComponentCard title="Search Coupon">
        <form onSubmit={handleSearch} className="space-y-4">
          <div>
            <Label>Coupon Code</Label>
            <div className="flex gap-3">
              <Input
                type="text"
                value={couponCode}
                onChange={(e) => setCouponCode(e.target.value.toUpperCase())}
                placeholder="Enter coupon code (e.g., ABC123)"
                disabled={loading}
                className="uppercase flex-1"
              />
              <Button type="submit" disabled={loading || !couponCode.trim()}>
                {loading ? "Searching..." : "Search"}
              </Button>
            </div>
            <p className="text-sm text-gray-500 mt-1">
              Enter the coupon code to view its details and usage history
            </p>
          </div>
        </form>
      </ComponentCard>

      {/* Coupon Details */}
      {searched &&
        (couponData ? (
          <ComponentCard title="Coupon Details">
            <div className="space-y-4">
              {/* Header */}
              <div className="flex items-start justify-between pb-4 border-b border-gray-200 dark:border-gray-700">
                <div>
                  <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100">
                    {couponData.code}
                  </h3>
                  <p className="text-sm text-gray-500 mt-1">Coupon Details</p>
                </div>
                <span
                  className={`px-3 py-1 text-xs font-semibold rounded ${getStatusColor(
                    couponData.status
                  )}`}
                >
                  {couponData.status || "ACTIVE"}
                </span>
              </div>

              {/* Details Grid */}
              <div className="grid md:grid-cols-2 gap-6">
                {/* Left Column */}
                <div className="space-y-4">
                  <div>
                    <p className="text-sm text-gray-500 mb-1">Generated By</p>
                    <div className="flex items-center gap-2">
                      <UserIcon className="w-4 h-4 text-gray-400" />
                      <span className="font-medium">
                        {couponData.generatedBy?.name || "N/A"}
                      </span>
                    </div>
                    {couponData.generatedBy?.email && (
                      <p className="text-sm text-gray-500 ml-6">
                        {couponData.generatedBy.email}
                      </p>
                    )}
                  </div>

                  <div>
                    <p className="text-sm text-gray-500 mb-1">Generated On</p>
                    <div className="flex items-center gap-2">
                      <CalenderIcon className="w-4 h-4 text-gray-400" />
                      <span className="font-medium">
                        {couponData.createdAt
                          ? new Date(couponData.createdAt).toLocaleString("en-US", {
                              year: "numeric",
                              month: "short",
                              day: "numeric",
                              hour: "2-digit",
                              minute: "2-digit",
                            })
                          : "N/A"}
                      </span>
                    </div>
                  </div>

                  {couponData.discount && (
                    <div>
                      <p className="text-sm text-gray-500 mb-1">Discount Value</p>
                      <div className="flex items-center gap-2">
                        <span className="font-medium text-lg text-success-600">
                          {couponData.discountType === "PERCENTAGE"
                            ? `${couponData.discount}%`
                            : formatUSD(Number(couponData.discount))}
                        </span>
                      </div>
                    </div>
                  )}
                </div>

                {/* Right Column */}
                <div className="space-y-4">
                  {couponData.honoredBy && (
                    <div>
                      <p className="text-sm text-gray-500 mb-1">Honored By</p>
                      <div className="flex items-center gap-2">
                        <UserIcon className="w-4 h-4 text-gray-400" />
                        <span className="font-medium">{couponData.honoredBy.name || "N/A"}</span>
                      </div>
                      {couponData.honoredBy.email && (
                        <p className="text-sm text-gray-500 ml-6">{couponData.honoredBy.email}</p>
                      )}
                    </div>
                  )}

                  {couponData.honoredAt && (
                    <div>
                      <p className="text-sm text-gray-500 mb-1">Honored On</p>
                      <div className="flex items-center gap-2">
                        <CalenderIcon className="w-4 h-4 text-gray-400" />
                        <span className="font-medium">
                          {new Date(couponData.honoredAt).toLocaleString("en-US", {
                            year: "numeric",
                            month: "short",
                            day: "numeric",
                            hour: "2-digit",
                            minute: "2-digit",
                          })}
                        </span>
                      </div>
                    </div>
                  )}

                  {couponData.expiresAt && (
                    <div>
                      <p className="text-sm text-gray-500 mb-1">Expires On</p>
                      <div className="flex items-center gap-2">
                        <CalenderIcon className="w-4 h-4 text-gray-400" />
                        <span className="font-medium">
                          {new Date(couponData.expiresAt).toLocaleDateString("en-US", {
                            year: "numeric",
                            month: "short",
                            day: "numeric",
                          })}
                        </span>
                      </div>
                    </div>
                  )}
                </div>
              </div>

              {/* Description */}
              {couponData.description && (
                <div className="pt-4 border-t border-gray-200 dark:border-gray-700">
                  <p className="text-sm text-gray-500 mb-2">Description</p>
                  <p className="text-gray-700 dark:text-gray-300">{couponData.description}</p>
                </div>
              )}

              {/* Customer Info */}
              {couponData.customerEmail && (
                <div className="pt-4 border-t border-gray-200 dark:border-gray-700">
                  <p className="text-sm text-gray-500 mb-2">Customer Information</p>
                  <div className="flex items-center gap-2">
                    <span className="text-gray-700 dark:text-gray-300">
                      {couponData.customerEmail}
                    </span>
                  </div>
                </div>
              )}
            </div>
          </ComponentCard>
        ) : (
          <ComponentCard>
            <div className="text-center py-8">
              <span className="text-5xl mb-3 block">🔍</span>
              <h3 className="text-lg font-semibold mb-2 text-gray-800 dark:text-white/90">
                Coupon Not Found
              </h3>
              <p className="text-gray-600 dark:text-gray-400">
                The coupon code you entered does not exist in the system.
              </p>
            </div>
          </ComponentCard>
        ))}

      {/* Info Box */}
      <ComponentCard>
        <div className="p-4 bg-brand-50 dark:bg-brand-900/20 border-l-4 border-brand-500 rounded-lg">
          <div className="flex items-start gap-3">
            <InfoIcon className="w-5 h-5 text-brand-600 flex-shrink-0 mt-0.5" />
            <div className="text-sm text-gray-700 dark:text-gray-300">
              <strong>Audit Purpose:</strong> Use this tool to verify coupon authenticity, check
              usage history, and ensure coupons are being used correctly by employees.
            </div>
          </div>
        </div>
      </ComponentCard>
    </div>
  );
}

